CREATE TABLE MANAGE_LOAN
( ID                                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY
, EVENT_ID                            VARCHAR2(36 CHAR)         NOT NULL
, PERSON_ID                           VARCHAR2(36 CHAR)         NOT NULL
, AMOUNT                              DOUBLE(19)                NOT NULL
, DETAILS                             VARCHAR2(255 CHAR)
, REGISTERED_TIMESTAMP                TIMESTAMP                 NOT NULL
, VALIDATED_TIMESTAMP                 TIMESTAMP
, ENRICHED_TIMESTAMP                  TIMESTAMP
, PENDING_TIMESTAMP                   TIMESTAMP
, AUGMENTED_TIMESTAMP                 TIMESTAMP
, ENTITLED_TIMESTAMP                  TIMESTAMP
, REJECTED_TIMESTAMP                  TIMESTAMP
, CONSTRAINT MANAGE_LOAN_PK           PRIMARY KEY (ID)
, CONSTRAINT MANAGE_LOAN_EVENT_ID_UC  UNIQUE (EVENT_ID)
);