CREATE TABLE PERSON
( ID                                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY
, PERSON_ID                         VARCHAR2(36 CHAR)         NOT NULL
, SSN                               VARCHAR2(11 CHAR)         NOT NULL
, BIRTH_DATE                        DATE                      NOT NULL
, GENDER                            VARCHAR2(1 CHAR)          NOT NULL
, FIRST_NAME                        VARCHAR2(50 CHAR)         NOT NULL
, LAST_NAME                         VARCHAR2(50 CHAR)         NOT NULL
, NATIONALITY                       VARCHAR2(2 CHAR)          NOT NULL
, CONSTRAINT PERSON_PK              PRIMARY KEY (ID)
, CONSTRAINT PERSON_PERSONAL_ID_UC  UNIQUE (PERSON_ID)
, CONSTRAINT PERSON_SSN_UC          UNIQUE (SSN)
);